# Generated by Django 5.2.4 on 2025-07-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
    ]
